server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    # Notice the DB_USER and DB_PASSWORD variables below
    url: jdbc:mysql://${DB_HOST}:3306/auth_db_banking?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    expiration-ms: ${SECURITY_JWT_EXPIRATION_MS:3600000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
