server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/user_db_banking?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    expiration-ms: ${SECURITY_JWT_EXPIRATION_MS:3600000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
